### ISSUE TITLE
`ListAsync` parsing error

### ISSUE THREAD

**Issue by Swimburger** [AssemblyAI/assemblyai-csharp-sdk#36]
When I run the `Should_Paginate_Transcripts` test, I get this error:
```
System.Text.Json.JsonException : The JSON value could not be converted to System.DateTime. Path: $.transcripts[7].completed | LineNumber: 0 | BytePosi...

System.Text.Json.JsonException : The JSON value could not be converted to System.DateTime. Path: $.transcripts[7].completed | LineNumber: 0 | BytePositionInLine: 3040.
  ----> System.InvalidOperationException : Cannot get the value of a token type 'Null' as a string.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at AssemblyAI.TranscriptsClient.ListAsync(ListTranscriptParams request) in /Users/niels/assemblyai-csharp-sdk/src/AssemblyAI/Transcripts/TranscriptsClient.cs:line 61
   at AssemblyAI.Test.TranscriptsClientTests.Should_Paginate_Transcripts() in /Users/niels/assemblyai-csharp-sdk/src/AssemblyAI.Test/TranscriptsClientTests.cs:line 201
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--InvalidOperationException
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& value)
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)



-----

One or more child tests had errors
  Exception doesn't have a stacktrace
```

**Comment by dcb6** [comment]
@Swimburger looks like this is because the `Completed` property is non-nullable, but we can receive `null` for the property. Example here:

```json
    {
      "id": "8fec92e3-a2fe-41ae-803c-b93865d6a4a3",
      "resource_url": "https://api.assemblyai.com/v2/transcript/8fec92e3-a2fe-41ae-803c-b93865d6a4a3",
      "status": "error",
      "created": "2024-07-29T17:25:33.497510",
      "completed": null,
      "audio_url": "https://cdn.assemblyai.com/upload/87c38197-5b74-4109-87c2-5a94aa38811b",
      "error": "File does not appear to contain audio. File type is audio/x-wav (RIFF (little-endian) data, WAVE audio)."
    },
```

Up to change this in your api spec? As usual, this would potentially be a breaking change for other SDKs, but again probably a good break. If you only want it to apply to csharp, we can change the type of this field in the csharp overrides in [this PR](https://github.com/AssemblyAI/assemblyai-api-spec/pull/107/files)

**Comment by Swimburger** [comment]
@dcb6 `completed` is marked as a string or null in the spec.

**Comment by dcb6** [comment]
looks like the `x-fern-type` is not optional:
```
        completed:
          x-label: Completed
          type: [string, "null"]
          pattern: '^(?:(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2}(?:\.\d+)?))$'
          x-fern-type: datetime    <------------ This needs to be optional<datetime>
          x-ts-type: Date | null
```

**Comment by Swimburger** [comment]
Fixed in spec: https://github.com/AssemblyAI/assemblyai-api-spec/pull/112
